// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Client.proto

// Protobuf Java Version: 3.25.1
package real.grpc.client;

public interface MoveRelativeCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:real.grpc.client.MoveRelativeCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float x = 1;</code>
   * @return The x.
   */
  float getX();

  /**
   * <code>float y = 2;</code>
   * @return The y.
   */
  float getY();

  /**
   * <code>float theta = 3;</code>
   * @return The theta.
   */
  float getTheta();
}
