// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Client.proto

// Protobuf Java Version: 3.25.1
package real.grpc.client;

public interface MoveResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:real.grpc.client.MoveResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();
}
