// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Client.proto

// Protobuf Java Version: 3.25.1
package real.grpc.client;

public interface PingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:real.grpc.client.PingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 robot_id = 1;</code>
   * @return The robotId.
   */
  int getRobotId();
}
