# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63lient.proto\x12\x10real.grpc.client\"\x07\n\x05\x45mpty\" \n\x0cPingResponse\x12\x10\n\x08robot_id\x18\x01 \x01(\x05\"\x1f\n\x0cMoveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\":\n\x13MoveRelativeCommand\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05theta\x18\x03 \x01(\x02\x32\x9e\x01\n\x06\x43lient\x12\x41\n\x04Ping\x12\x17.real.grpc.client.Empty\x1a\x1e.real.grpc.client.PingResponse\"\x00\x12Q\n\x06MoveTo\x12%.real.grpc.client.MoveRelativeCommand\x1a\x1e.real.grpc.client.MoveResponse\"\x00\x42\x02P\x01\x62\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_PINGRESPONSE = DESCRIPTOR.message_types_by_name['PingResponse']
_MOVERESPONSE = DESCRIPTOR.message_types_by_name['MoveResponse']
_MOVERELATIVECOMMAND = DESCRIPTOR.message_types_by_name['MoveRelativeCommand']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:real.grpc.client.Empty)
  })
_sym_db.RegisterMessage(Empty)

PingResponse = _reflection.GeneratedProtocolMessageType('PingResponse', (_message.Message,), {
  'DESCRIPTOR' : _PINGRESPONSE,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:real.grpc.client.PingResponse)
  })
_sym_db.RegisterMessage(PingResponse)

MoveResponse = _reflection.GeneratedProtocolMessageType('MoveResponse', (_message.Message,), {
  'DESCRIPTOR' : _MOVERESPONSE,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:real.grpc.client.MoveResponse)
  })
_sym_db.RegisterMessage(MoveResponse)

MoveRelativeCommand = _reflection.GeneratedProtocolMessageType('MoveRelativeCommand', (_message.Message,), {
  'DESCRIPTOR' : _MOVERELATIVECOMMAND,
  '__module__' : 'client_pb2'
  # @@protoc_insertion_point(class_scope:real.grpc.client.MoveRelativeCommand)
  })
_sym_db.RegisterMessage(MoveRelativeCommand)

_CLIENT = DESCRIPTOR.services_by_name['Client']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _EMPTY._serialized_start=34
  _EMPTY._serialized_end=41
  _PINGRESPONSE._serialized_start=43
  _PINGRESPONSE._serialized_end=75
  _MOVERESPONSE._serialized_start=77
  _MOVERESPONSE._serialized_end=108
  _MOVERELATIVECOMMAND._serialized_start=110
  _MOVERELATIVECOMMAND._serialized_end=168
  _CLIENT._serialized_start=171
  _CLIENT._serialized_end=329
# @@protoc_insertion_point(module_scope)
